### ISSUE TITLE
Does not install properly

### ISSUE THREAD

**Issue by olivier-haddad** [twsouthwick/NuGetPackageConfigConverter#13]
### Installed product versions
- Visual Studio: [ 2015 Enterprise] Update 3
- This extension: [example 1.1.21]

### Description
The install complete without errors but there are two problems:
1.The extention appears in Help/About as VSPackage1 and not the meaning name.
2.Upon loading a solution, an error message about the "VSPackage" extension appear and it is not loaded.

### Steps to recreate
See above.

**Comment by wislon** [comment]
@olivier-haddad I had the same issue, yesterday on VS2015 Enterprise.

It seems to be a problem with the way it's detecting the Visual Studio version (if you open that `ActivityLog.xml` mentioned by the error message, the xml shows that it can't locate Visual Studio 14, right at the bottom).

I figured it probably worked before the most recent commit (in May), so I cloned the repo/master branch, reset the source to the second last commit, and opened it. Then I had to install the VS extensibility tools (which VS helpfully did for me). 

Restarted VS after that was done, opened this solution *again* and rebuilt it. That made a `vsix` file in the `bin\Debug` folder, which I then installed. 

After restarting VS, I opened my testing solution, and there was no `VSPackage` error, and the option to convert was there, as expected. 

I hope that helps you work around this problem?

**Comment by wislon** [comment]
Some more info: Here's a screenshot of the error

![vspackage-error](https://user-images.githubusercontent.com/1695185/27108284-9bbff176-50df-11e7-82a9-63290e6e97d4.jpg)

Note that this happens when you actually open a solution. If you just open VS by itself, there's no error.

Here's the xml from the activity log file mentioned in that error message:

```xml
  <entry>
    <record>603</record>
    <time>2017/06/13 22:54:00.700</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>CreateInstance failed for package [VSPackage]Source: &apos;mscorlib&apos; Description: Could not load file or assembly &apos;Microsoft.VisualStudio.Shell.14.0, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&apos; or one of its dependencies. The system cannot find the file specified.&#x000D;&#x000A;System.IO.FileNotFoundException: Could not load file or assembly &apos;Microsoft.VisualStudio.Shell.14.0, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&apos; or one of its dependencies. The system cannot find the file specified.&#x000D;&#x000A;File name: &apos;Microsoft.VisualStudio.Shell.14.0, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&apos;&#x000D;&#x000A;   at System.Reflection.RuntimeAssembly.GetType(RuntimeAssembly assembly, String name, Boolean throwOnError, Boolean ignoreCase, ObjectHandleOnStack type)&#x000D;&#x000A;   at System.Reflection.RuntimeAssembly.GetType(String name, Boolean throwOnError, Boolean ignoreCase)&#x000D;&#x000A;   at System.Activator.CreateInstanceFromInternal(String assemblyFile, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo)&#x000D;&#x000A;   at System.AppDomain.CreateInstanceFrom(String assemblyFile, String typeName)&#x000D;&#x000A;&#x000D;&#x000A;WRN: Assembly binding logging is turned OFF.&#x000D;&#x000A;To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.&#x000D;&#x000A;Note: There is some performance penalty associated with assembly bind failure logging.&#x000D;&#x000A;To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].&#x000D;&#x000A;</description>
    <guid>{D0C73E24-D906-4D3F-AB3C-4F5B6758394C}</guid>
    <hr>80004005 - E_FAIL</hr>
    <errorinfo></errorinfo>
  </entry>
```

**Comment by twsouthwick** [comment]
Hmmm - interesting. I'm actually removing VS 2015 support to be able to more easily support VS 2017 and PackageReference. If that doesn't work for you please reopen and let me know.

**Comment by tijana88** [comment]
Hi @twsouthwick I'm also having same error as reported by wislon using VS2015 and latest version of tool. Is fix in plan? 
I've tried to rebuild .sln from commit in 17.10.2016 and I no longer have the error when loading .sln but if I click on convert I get error:
![conversion](https://user-images.githubusercontent.com/9393050/30208663-d0abaad0-9494-11e7-8e15-b64058105c74.png)
