### ISSUE TITLE
Conversion of non-trivial projects is extremely slow or hangs

### ISSUE THREAD

**Issue by ahukin** [twsouthwick/NuGetPackageConfigConverter#16]
### Installed product versions
- Visual Studio: 2017 Enterprise 
- This extension: 0.1.30 (from Visual Studio Marketplace)
- Project types within the solution being converted: project.json, packages.config, and various platforms: full .net, PCL, iOS, Android, UWP

### Description
I was doing a bit of learning and set up the Azure Mobile App Quickstart (see Azure (that's what I did) or you can get the code here https://github.com/Azure/azure-mobile-apps-quickstarts).  I set up the Azure server (well, Azure did it for me) and downloaded the Xamarin.Forms mobile client app source code that was prepared by the Azure site. It all built and ran fine.

I decide to try using the NuGetPackageConfigConverter to upgrade the source to the new csproj format but it seemed to get stuck/hang.  I killed Visual Studio a few times, rebooted, restored the code and tried again.  Nothing seemed to work.  I eventually decided to look and see whether any files were being updated and I noticed that the modification time was changing on the csproj and packages.config file and the files did actually seem to have changed.  I continued to monitor and could see that the files were being updated every now and then although the UI seemed to be frozen.

I left the NuGetPackageConfigConverter to run overnight and in the morning it seemed to have moved on to a new csproj but still had a few projects to go.  I killed the extension but because it seems to leave some of the work until the end, none of the projects had been successfully upgraded.

In case there was something odd about this code (it wasn't mine so who knows), I thought I'd try it out on one of our apps but, because I realised that some of the work didn't get completed until the end, I created a new solution and only added the projects to it one at a time and ran the NuGetPackageConfigConverter on solution in between so that I could get at least some of the projects converted.

About the first 6 projects converted fine: add a project to the solution, run the converter, repeat.  Some were quite slow but (30 minutes) but others quite fast (a minute).  Adding projects didn't seem to affect the speed i.e. it didn't seem to gradually get slower - conversion speed seemed to depend on the project just added and not on the number of already converted projects in the solution.  Then one project just seemed to take forever and I have left it running overnight.  Still no luck in the morning but I think it is still doing something.  I'll post back about it later.

I expect the conversion may depend on the complexity of the project with an exponential(?) increase in time.  Then again, it may just be a bug.

Otherwise I quite like it ;-)

**Comment by twsouthwick** [comment]
So there is part of the algorithm that is `n^2` where `n` is the number of dependencies you have. This is the worst case scenario, and could be as good as `n` in best. However, the only way to fix this is to find the dependency graph of all the dependencies and I'm not sure how to do that. I end up trying to remove a dependency, and if it doesn't, I move on the to the next. Removing a dependency will fail when there are others that are dependending on it, but in packages.config, that is an unknown AFAIK.

I have just pushed a fix that will help with some of the time (I was failing to account for retries correctly). I'll leave this open to maybe address the `O(n^2)` aspect

**Comment by twsouthwick** [comment]
This project will not be maintained as support for converting to PackageReference is included in VS 15.7+: https://docs.microsoft.com/en-us/nuget/reference/migrate-packages-config-to-package-reference
