### ISSUE TITLE
 Visual Studio: [example 2017 Professional]

### ISSUE THREAD

**Issue by maclife** [twsouthwick/NuGetPackageConfigConverter#17]
### Installed product versions
- Visual Studio: [example 2017 Professional]
- This extension: [example 1.1.21]
- Project types within the solution being converted

### Description
Replace this text with a short description

### Steps to recreate
1. Replace this
2. text with 
3. the steps
4. to recreate

### Current behavior
Explain what it's doing and why it's wrong

### Expected behavior
Explain what it should be doing after it's fixed.

**Comment by twsouthwick** [comment]
@maclife There doesn't seem to be any issue (you've just included the template). I'll close this, but feel free to open and edit with your issue!
