### ISSUE TITLE
Allow converting single project

### ISSUE THREAD

**Issue by PhilPJL** [twsouthwick/NuGetPackageConfigConverter#19]
Visual Studio 2017

we have a solution containing 180 projects.
If I try to convert all of them it will take an extremely long time to run and will also cause chaso because removing and re-adding some nuget packages does not work successfully when using TFS 2012 (any maybe later) because TFS can't handle the same file being deleted and then added back.  Which is another reason to do the conversion one project at a time.

**Comment by twsouthwick** [comment]
This project will not be maintained as support for converting to PackageReference is included in VS 15.7+: https://docs.microsoft.com/en-us/nuget/reference/migrate-packages-config-to-package-reference
