### ISSUE TITLE
Unable to delete packages.config

### ISSUE THREAD

**Issue by ericnewton76** [twsouthwick/NuGetPackageConfigConverter#33]
### Installed product versions
- Visual Studio: 2017 Professional
- This extension: [example 1.1.21]
- Project types within the solution being converted: Web application

### Description
error occurred converting to PackageReferences

### Steps to recreate
!!! I just realized I was in VS Debug mode which probably created the problem !!!
Right click Solution, select "Upgrade to PackageReferences"

### Current behavior
Error dialog encountered:
failed to delete packages.config... !!! because VS was in Debug mode !!!

### Expected behavior
Successful operation, or command unavailable when VS is in Debug mode.

[NuGetPackageConfigConverter error.txt](https://github.com/twsouthwick/NuGetPackageConfigConverter/files/2457000/NuGetPackageConfigConverter.error.txt)

**Comment by twsouthwick** [comment]
This project will not be maintained as support for converting to PackageReference is included in VS 15.7+: https://docs.microsoft.com/en-us/nuget/reference/migrate-packages-config-to-package-reference
