### ISSUE TITLE
"Convert packages.config to project.json" does not show up in Solution Explorer

### ISSUE THREAD

**Issue by conniey** [twsouthwick/NuGetPackageConfigConverter#5]
### Installed product versions
- Visual Studio: 2015 Enterprise with Update 3 (14.0.25431.01)
- This extension: 0.1.8
### Description

I cannot invoke the extension because it does not appear in the context menu even though the extension is enabled.
### Steps to recreate
1. `git clone https://github.com/microsoft/dotnet-apiport`
2. Open PortabilityTools.sln 
3. Right-click on PortabilityTools solution in Solution Explorer
### Current behavior

Notice that the context menu item is not there.
![image](https://cloud.githubusercontent.com/assets/10136526/19058171/08da673c-898a-11e6-8257-94e76ea3413d.png)
### Expected behavior

That I see the context menu item

**Comment by twsouthwick** [comment]
The root cause is described in #3. The fix was in the CI build - I've pushed it to the VS Gallery as well.

btw - I found the issue trying it on the same project :)
