### ISSUE TITLE
VSPackage Error Failing to Load extension

### ISSUE THREAD

**Issue by berlamont** [twsouthwick/NuGetPackageConfigConverter#6]
- Visual Studio: 2015 Enterprise
- Extension Ver 0.1.9

Heres the error text:
CreateInstance failed for package [VSPackage]
Source: 'mscorlib' 
Description: Could not load file or assembly 'file:///C:\USERS\XXXXX\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\14.0\EXTENSIONS\tpzijwnk.zb5\NuGetPackageConfigConverter.dll' or one of its dependencies. 
The system cannot find the file specified. System.IO.FileNotFoundException: Could not load file or assembly 'file:///C:\USERS\XXXXX\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\14.0\EXTENSIONS\tpzijwnk.zb5\NuGetPackageConfigConverter.dll' or one of its dependencies. 
The system cannot find the file specified. 
File name: 'file:///C:\USERS\XXXX\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\14.0\EXTENSIONS\tpzijwnk.zb5\NuGetPackageConfigConverter.dll' at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks) at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks) at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks) at System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte[] hashValue, AssemblyHashAlgorithm hashAlgorithm, Boolean forIntrospection, Boolean suppressSecurityChecks, StackCrawlMark& stackMark) at System.Reflection.Assembly.LoadFrom(String assemblyFile, Evidence securityEvidence) at System.Activator.CreateInstanceFromInternal(String assemblyFile, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo) at System.AppDomain.CreateInstanceFrom(String assemblyFile, String typeName) WRN: Assembly binding logging is turned OFF.
 To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog](DWORD) to 1. Note: There is some performance penalty associated with assembly bind failure logging. To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].
### Current behavior

Extension fails to load on startup

**Comment by twsouthwick** [comment]
Thanks, @berlamont  for the report. I'll need some more info to root cause this. Which version of VS2015 do you have?

**Comment by twsouthwick** [comment]
Could you list the contents of `C:\USERS\XXXX\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\14.0\EXTENSIONS\tpzijwnk.zb5`?

**Comment by berlamont** [comment]
When I get back to my box I'll try to get the contents of that directory, but I'm running VS 2015 update 3 on Win 10 Enterprise Anniversary Edition

**Comment by twsouthwick** [comment]
Ok - also, please update to the newest version as well

**Comment by twsouthwick** [comment]
@berlamont Any news on this? If you can download the latest version and let me know if it still repros we can troubleshoot some more.

**Comment by berlamont** [comment]
Hey sorry I kind of forgot about this, but it does indeed install now and seems to work pretty good thank you!

**Comment by twsouthwick** [comment]
No problem - good to hear it works now!
