### ISSUE TITLE
Empty project.json added to shared projects causes NuGet failure

### ISSUE THREAD

**Issue by ChrisMaddock** [twsouthwick/NuGetPackageConfigConverter#9]
Thanks for making this project available - it's been a massive timesaver for me, not being completely familiar with the latest changes to package restore! Just had one issue with the latest project, below:

### Installed product versions
- Visual Studio: VS 2015 update 3
- This extension: 0.1.16

### Description
The extension adds an empty project.json to shared projects, as below.
```
{
  "dependencies": {
  },
  "frameworks": {
    "": {}
  },
  "runtimes": {
    "win": {}
  }
}
```

This errors NuGet restore on the solution, with the following message:

```
Project nunit.runner is not compatible with unsupported (Unsupported,Version=v0.0). Project nunit.runner supports: unsupported (Unsupported,Version=v0.0)
```

I assume project.json shouldn't be added to shared projects? Removing the file and references allows restore to complete. As I say - haven't had a vast amount of experience here, apologies if this is actually a NuGet issue!

### Steps to recreate
1. Clone this: https://github.com/nunit/nunit.xamarin/tree/677973e07159c3e43b8793c68e9c17d9f45c2065
2. Run the extension
3. NuGet restore on the solution file

**Comment by twsouthwick** [comment]
I just noticed that it added this as well. I'll look into it. For now, feel free to just remove the project.json from the shared project. It doesn't need to be there.

**Comment by twsouthwick** [comment]
I've switched the tooling to use more of the NuGet built in package installation and the destination is PackageReference, so this will not occur.
